"""Add file_data to Resume

Revision ID: f273a5078cc6
Revises: 0001_initial_schema
Create Date: 2026-07-18 12:01:06.698392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f273a5078cc6'
down_revision: Union[str, None] = '0001_initial_schema'
"""Add file_data to Resume

Revision ID: f273a5078cc6
Revises: 0001_initial_schema
Create Date: 2026-07-18 12:01:06.698392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f273a5078cc6'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_data')
    op.alter_column('embeddings', 'vector_reference',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    # ### end Alembic commands ###
